#!/bin/bash


PHP_VERSION="8.1"
DockerName="larahost"

while [ -n "$1" ]; do
  case "$1" in
  -php8.1)
    PHP_VERSION="8.1"
    ;;
  -php8.0)
    PHP_VERSION="8.0"
    ;;
  -php7.4)
    PHP_VERSION="7.4"
    ;;
  *) echo "$1 is not an option" ;;
  esac
  shift
done

echo "building: larahost:$PHP_VERSION"

docker build --build-arg PHP_VERSION=$PHP_VERSION -t larahost:$PHP_VERSION .
docker image tag larahost:$PHP_VERSION humaid/larahost:$PHP_VERSION
#docker image push humaid/larahost:$PHP_VERSION
