#!/bin/bash


PHP_VERSION="8.1"
DevelopmentMode=false
DockerName="larahost"
TagName="8.1"

while [ -n "$1" ]; do
  case "$1" in
  -php8.1)
    PHP_VERSION="8.1"
    ;;
  -php8.0)
    PHP_VERSION="8.0"
    ;;
  -php7.4)
    PHP_VERSION="7.4"
    ;;
  -dev)
    DevelopmentMode=true
    ;;
  *) echo "$1 is not an option" ;;
  esac
  shift
done

if [[ "$DevelopmentMode" = "true" ]]; then
    TagName="${PHP_VERSION}-dev"
else
  TagName="${PHP_VERSION}"
fi

echo "building: larahost:$TagName"

docker build --build-arg DevelopmentBuild=$DevelopmentMode --build-arg PHP_VERSION=$PHP_VERSION -t larahost:$TagName .
docker image tag larahost:$TagName humaid/larahost:$TagName
docker image push humaid/larahost:$TagName
